import type {
  Company,
  CurrentUser,
  Customer,
  Estimate,
  PriceItem,
} from "./types";

export const company: Company = {
  name: "〇〇株式会社",
  postalCode: "444-0123",
  address: "愛知県額田郡幸田町大字芦谷字○○1-2-3",
  phone: "0564-00-0000",
  email: "info@kouta-tosou.example.jp",
  representativeName: "代表取締役 近藤 健一",
  invoiceRegistrationNo: "T1234567890123",
  bankAccountText: "○○銀行 幸田支店 普通 1234567 コウタトソウコウギョウ（カ",
  defaultNote:
    "・本見積の有効期限は発行日より30日間です。\n・工事金額は現地状況により変動する場合があります。",
};

export const currentUser: CurrentUser = {
  id: "user-001",
  name: "山田 涼",
  role: "admin",
};

export const priceItems: PriceItem[] = [
  { id: "p-001", name: "シリコン塗装", unit: "㎡", unitPrice: 4000, isActive: true },
  { id: "p-002", name: "水性塗装", unit: "㎡", unitPrice: 3000, isActive: true },
  { id: "p-003", name: "足場", unit: "㎡", unitPrice: 1000, isActive: true },
  { id: "p-004", name: "高圧洗浄", unit: "㎡", unitPrice: 500, isActive: true },
  { id: "p-005", name: "クッションフロア貼替", unit: "㎡", unitPrice: 4000, isActive: true },
  { id: "p-006", name: "クロス 貼替", unit: "㎡", unitPrice: 1300, isActive: true },
  { id: "p-007", name: "ソフト巾木", unit: "ｍ", unitPrice: 600, isActive: true },
  { id: "p-008", name: "フロアタイル", unit: "㎡", unitPrice: 6000, isActive: true },
  { id: "p-009", name: "コンセントプレート", unit: "個", unitPrice: 500, isActive: true },
  { id: "p-010", name: "火災報知器取付", unit: "個", unitPrice: 5000, isActive: true },
  { id: "p-011", name: "ペーパーホルダ", unit: "個", unitPrice: 5000, isActive: true },
  { id: "p-012", name: "鏡交換", unit: "個", unitPrice: 20000, isActive: true },
  { id: "p-013", name: "透明 ガラス", unit: "個", unitPrice: 18000, isActive: true },
  { id: "p-014", name: "パッキン交換", unit: "式", unitPrice: 2000, isActive: true },
  { id: "p-015", name: "カートリッジ交換", unit: "個", unitPrice: 12000, isActive: true },
  { id: "p-016", name: "フレキ交換", unit: "個", unitPrice: 5000, isActive: true },
  { id: "p-017", name: "ボールタップ交換", unit: "個", unitPrice: 9000, isActive: true },
  { id: "p-018", name: "ゴムフロート交換", unit: "個", unitPrice: 6000, isActive: true },
  { id: "p-019", name: "タンクレバー交換", unit: "個", unitPrice: 5000, isActive: true },
  { id: "p-020", name: "温水洗浄便座", unit: "個", unitPrice: 40000, isActive: true },
  { id: "p-021", name: "洗面台交換", unit: "個", unitPrice: 60000, isActive: true },
  { id: "p-022", name: "クリーニング　 １Ｋ", unit: "式", unitPrice: 28000, isActive: true },
  { id: "p-023", name: "クリーニング　 １ＬＤＫ", unit: "式", unitPrice: 30000, isActive: true },
  { id: "p-024", name: "クリーニング 　２ＤＫ", unit: "式", unitPrice: 30000, isActive: true },
  { id: "p-025", name: "クリーニング　 ２ＬＤＫ", unit: "式", unitPrice: 35000, isActive: true },
  { id: "p-026", name: "クリーニング　 ３ＤＫ", unit: "式", unitPrice: 35000, isActive: true },
  { id: "p-027", name: "クリーニング 　３ＬＤＫ", unit: "式", unitPrice: 40000, isActive: true },
  { id: "p-028", name: "スイッチ交換", unit: "個", unitPrice: 1800, isActive: true },
  { id: "p-029", name: "換気扇交換交換", unit: "個", unitPrice: 30000, isActive: true },
  { id: "p-030", name: "モニターホン交換", unit: "個", unitPrice: 30000, isActive: true },
  { id: "p-031", name: "網戸貼替", unit: "個", unitPrice: 3000, isActive: true },
  { id: "p-032", name: "シリコン", unit: "式", unitPrice: 4000, isActive: true },
  { id: "p-033", name: "シャワーホース", unit: "個", unitPrice: 5000, isActive: true },
  { id: "p-034", name: "電池交換", unit: "式", unitPrice: 800, isActive: true },
  { id: "p-035", name: "諸経費", unit: "式", unitPrice: 0, isActive: true },
];

export const customers: Customer[] = [
  {
    id: "c-001",
    name: "田中 太郎",
    nameKana: "タナカ タロウ",
    postalCode: "444-0201",
    address: "愛知県岡崎市○○町1-1",
    phone: "090-0000-0001",
    email: "tanaka@example.com",
    contactName: "田中 太郎",
    note: "築18年戸建。前回は2年前に屋根補修。",
  },
  {
    id: "c-002",
    name: "鈴木建設 株式会社",
    nameKana: "スズキケンセツ",
    postalCode: "445-0001",
    address: "愛知県西尾市○○1-5",
    phone: "0563-00-0002",
    email: "info@suzuki-ken.example.com",
    contactName: "鈴木 一郎",
    note: "協力会社。複数現場あり。",
  },
  {
    id: "c-003",
    name: "佐藤 花子",
    nameKana: "サトウ ハナコ",
    postalCode: "444-0512",
    address: "愛知県額田郡幸田町○○2-3",
    phone: "090-0000-0003",
    email: "sato@example.com",
    contactName: "佐藤 花子",
    note: "内装リフォーム検討中。",
  },
  {
    id: "c-004",
    name: "山田工務店",
    nameKana: "ヤマダコウムテン",
    postalCode: "446-0001",
    address: "愛知県安城市○○3-7",
    phone: "0566-00-0004",
    email: "yamada@example.com",
    contactName: "山田 健",
    note: "退去立会い案件の相談あり。",
  },
  {
    id: "c-005",
    name: "高橋商店",
    nameKana: "タカハシショウテン",
    postalCode: "444-0007",
    address: "愛知県岡崎市○○4-2",
    phone: "0564-00-0005",
    email: "takahashi@example.com",
    contactName: "高橋 学",
    note: "店舗併用住宅。",
  },
];

export const estimates: Estimate[] = [
  {
    id: "est-001",
    estimateNo: "Q-2026-0042",
    customerId: "c-003",
    title: "1LDK 原状回復工事",
    estimateDate: "2026-06-03",
    expiresOn: "2026-07-03",
    status: "draft",
    assignee: "山田 涼",
    customerNote:
      "既存下地の状態により補修範囲が変動する場合があります。施工前に最終確認を行います。",
    internalInstruction:
      "退去後すぐの案件。クロス数量は現地採寸後に確定。管理会社向けには社内指示をPDFに出さないこと。",
    updatedAt: "2026-06-03T09:30:00",
    hasUnconfirmedAi: true,
    lines: [
      {
        id: "l-1",
        lineNo: 1,
        priceItemId: "p-006",
        location: "居室・廊下",
        itemName: "クロス 貼替",
        quantity: 45,
        unit: "㎡",
        unitPrice: 1300,
        lineType: "normal",
      },
      {
        id: "l-2",
        lineNo: 2,
        priceItemId: "p-005",
        location: "洋室",
        itemName: "クッションフロア貼替",
        quantity: 18,
        unit: "㎡",
        unitPrice: 4000,
        lineType: "normal",
      },
      {
        id: "l-3",
        lineNo: 3,
        priceItemId: "p-007",
        location: "居室・廊下",
        itemName: "ソフト巾木",
        quantity: 30,
        unit: "ｍ",
        unitPrice: 600,
        lineType: "normal",
      },
      {
        id: "l-4",
        lineNo: 4,
        priceItemId: "p-009",
        location: "室内",
        itemName: "コンセントプレート",
        quantity: 8,
        unit: "個",
        unitPrice: 500,
        lineType: "normal",
      },
      {
        id: "l-5",
        lineNo: 5,
        priceItemId: "p-023",
        location: "全体",
        itemName: "クリーニング　 １ＬＤＫ",
        quantity: 1,
        unit: "式",
        unitPrice: 30000,
        lineType: "normal",
      },
    ],
  },
  {
    id: "est-002",
    estimateNo: "Q-2026-0041",
    customerId: "c-001",
    title: "外壁シリコン塗装工事",
    estimateDate: "2026-06-01",
    expiresOn: "2026-07-01",
    status: "submitted",
    assignee: "山田 涼",
    customerNote:
      "足場・高圧洗浄・シリコン塗装を含みます。色見本はご契約後に確認します。",
    internalInstruction:
      "前面道路が狭いため足場搬入は朝イチ。北側隣地への養生を徹底する。",
    updatedAt: "2026-06-01T16:05:00",
    lines: [
      {
        id: "l2-1",
        lineNo: 1,
        priceItemId: "p-003",
        location: "外壁",
        itemName: "足場",
        quantity: 120,
        unit: "㎡",
        unitPrice: 1000,
        lineType: "normal",
        internalInstruction: "搬入経路が狭いので誘導員を1名手配。",
      },
      {
        id: "l2-2",
        lineNo: 2,
        priceItemId: "p-004",
        location: "外壁",
        itemName: "高圧洗浄",
        quantity: 120,
        unit: "㎡",
        unitPrice: 500,
        lineType: "normal",
      },
      {
        id: "l2-3",
        lineNo: 3,
        priceItemId: "p-001",
        location: "外壁",
        itemName: "シリコン塗装",
        quantity: 120,
        unit: "㎡",
        unitPrice: 4000,
        lineType: "normal",
        customerNote: "標準グレードのシリコン塗料を想定しています。",
      },
      {
        id: "l2-4",
        lineNo: 4,
        priceItemId: "p-032",
        location: "目地",
        itemName: "シリコン",
        quantity: 1,
        unit: "式",
        unitPrice: 4000,
        lineType: "normal",
      },
    ],
  },
  {
    id: "est-003",
    estimateNo: "Q-2026-0040",
    customerId: "c-002",
    title: "水回り設備交換",
    estimateDate: "2026-05-30",
    expiresOn: "2026-06-29",
    status: "draft",
    assignee: "佐藤 美咲",
    customerNote: "既存設備の撤去範囲は現地確認後に確定します。",
    internalInstruction: "品番未確定。発注前に管理会社承認を取る。",
    updatedAt: "2026-05-31T09:00:00",
    hasUnconfirmedAi: true,
    lines: [
      {
        id: "l3-1",
        lineNo: 1,
        priceItemId: "p-020",
        location: "トイレ",
        itemName: "温水洗浄便座",
        quantity: 1,
        unit: "個",
        unitPrice: 40000,
        lineType: "normal",
      },
      {
        id: "l3-2",
        lineNo: 2,
        priceItemId: "p-011",
        location: "トイレ",
        itemName: "ペーパーホルダ",
        quantity: 1,
        unit: "個",
        unitPrice: 5000,
        lineType: "normal",
      },
      {
        id: "l3-3",
        lineNo: 3,
        priceItemId: "p-012",
        location: "洗面",
        itemName: "鏡交換",
        quantity: 1,
        unit: "個",
        unitPrice: 20000,
        lineType: "normal",
      },
    ],
  },
  {
    id: "est-004",
    estimateNo: "Q-2026-0039",
    customerId: "c-004",
    title: "網戸・スイッチ交換",
    estimateDate: "2026-05-20",
    expiresOn: "2026-06-19",
    status: "won",
    assignee: "山田 涼",
    customerNote: "交換対象は現地で確認した箇所です。",
    internalInstruction: "入居前対応。作業完了写真を必ず残す。",
    updatedAt: "2026-05-22T11:30:00",
    lines: [
      {
        id: "l4-1",
        lineNo: 1,
        priceItemId: "p-031",
        location: "各窓",
        itemName: "網戸貼替",
        quantity: 4,
        unit: "個",
        unitPrice: 3000,
        lineType: "normal",
      },
      {
        id: "l4-2",
        lineNo: 2,
        priceItemId: "p-028",
        location: "室内",
        itemName: "スイッチ交換",
        quantity: 6,
        unit: "個",
        unitPrice: 1800,
        lineType: "normal",
      },
    ],
  },
  {
    id: "est-005",
    estimateNo: "Q-2026-0038",
    customerId: "c-005",
    title: "店舗原状回復工事",
    estimateDate: "2026-05-10",
    expiresOn: "2026-06-09",
    status: "lost",
    assignee: "佐藤 美咲",
    customerNote: "概算見積のため、実測後に再見積となります。",
    internalInstruction: "相見積で失注。次回は設備交換を分けて提案。",
    updatedAt: "2026-05-12T14:00:00",
    lines: [
      {
        id: "l5-1",
        lineNo: 1,
        priceItemId: "p-008",
        location: "店舗床",
        itemName: "フロアタイル",
        quantity: 30,
        unit: "㎡",
        unitPrice: 6000,
        lineType: "normal",
      },
      {
        id: "l5-2",
        lineNo: 2,
        priceItemId: "p-027",
        location: "全体",
        itemName: "クリーニング 　３ＬＤＫ",
        quantity: 1,
        unit: "式",
        unitPrice: 40000,
        lineType: "normal",
      },
    ],
  },
];

export function blankEstimate(id: string): Estimate {
  return {
    id,
    estimateNo: "（保存時に自動採番）",
    customerId: undefined,
    title: "",
    estimateDate: "2026-06-03",
    expiresOn: "2026-07-03",
    status: "draft",
    assignee: currentUser.name,
    customerNote: company.defaultNote,
    internalInstruction: "",
    updatedAt: "2026-06-03T09:00:00",
    lines: [],
  };
}

/** 既存見積を取得。見つからない（new等）場合は新規ドラフトを返す。 */
export function getEstimateOrBlank(id: string): {
  estimate: Estimate;
  isNew: boolean;
} {
  const found = getEstimate(id);
  if (found) return { estimate: found, isNew: false };
  return { estimate: blankEstimate(id), isNew: true };
}

export function getCustomer(id?: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getEstimate(id: string): Estimate | undefined {
  return estimates.find((e) => e.id === id);
}

export function customerName(id?: string): string {
  return getCustomer(id)?.name ?? "（顧客未選択）";
}